name: Build/deploy Package Nuget

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    env:
      PATH_PROJECT: "./Nuget/Nuget.csproj"
      SOURCE_NUGET: "https://api.nuget.org/v3/index.json"
      SOURCE_GITHUB: https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json
      USERNAME: "rcardososilva"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'    

    - name: Build 
      run: dotnet build ${{ env.PATH_PROJECT }} --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack ${{ env.PATH_PROJECT }} --configuration Release -o ${{ github.workspace }}/out

    - name: Deploy Nuget.org
      run: dotnet nuget push "${{ github.workspace }}/out/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.SOURCE_NUGET }} --skip-duplicate
   
    - name: Deploy Github Package      
      run: dotnet nuget push "${{ github.workspace }}/out/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.SOURCE_GITHUB }} --skip-duplicate
            
