name: Build/deploy Package Nuget

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-deploy:
    env:
      PATH_PROJECT: "./Nuget/Nuget.csproj"
      SOURCE_NUGET: "https://api.nuget.org/v3/index.json"
      SOURCE_GITHUB: https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json
      USERNAME: "rcardososilva"

    if: contains(github.head_ref, 'alpha') || contains(github.head_ref, 'beta') || contains(github.head_ref, 'prerelease')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'    

    - name: Build 
      run: dotnet build ${{ env.PATH_PROJECT }} --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack ${{ env.PATH_PROJECT }} --configuration Release -o ${{ github.workspace }}/out

    - name: Deploy Nuget.org
      run: dotnet nuget push "${{ github.workspace }}/out/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.SOURCE_NUGET }} --skip-duplicate
   
    - name: Deploy Github Package      
      run: dotnet nuget push "${{ github.workspace }}/out/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.SOURCE_GITHUB }} --skip-duplicate

    - name: Semantic Versioning
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: 'v'
        major_pattern: "break:"
        minor_pattern: "feat:"
        patch_pattern: "fix:"
        format: "v${major}.${minor}.${patch}-prerelease${increment}"         

    - name: Create Release
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.versioning.outputs.version }}
        release_name: ${{ steps.versioning.outputs.version }}
        prerelease: true