name: Build/deploy Package Nuget

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-deploy:
    env:
      PATH_PROJECT: "./Nuget/Nuget.csproj"
      SOURCE_NUGET: "https://api.nuget.org/v3/index.json"
      SOURCE_GITHUB: https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json
      USERNAME: "rcardososilva"

    if: contains(github.head_ref, 'alpha') || contains(github.head_ref, 'beta') || contains(github.head_ref, 'prerelease')

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'   

    - name: Find the specific suffix to compose the version format
      run: |
        import re
        import os
        github_head_ref = "${{ github.head_ref }}"
        name_branch = github_head_ref.lower()
        suffix_array = re.findall("alpha|beta|prerelease", name_branch)
        env_file = os.getenv('GITHUB_ENV')
        with open(env_file, "a") as myfile:
          myfile.write("PRERELEASE=" + suffix_array[0])
      shell: python
  
    - name: Set prerelease suffix as output
      id: get-prerelease-suffix
      run: echo "::set-output name=prerelease_suffix::$(echo $PRERELEASE)"
      shell: bash     

    - name: Semantic versioning
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: ''
        major_pattern: "break:"
        minor_pattern: "feat:"
        patch_pattern: "fix:"
        format: "${major}.${minor}.${patch}-${{ steps.prerelease-suffix-version.outputs.prerelease_suffix }}${increment}"

    - name: Build 
      run: dotnet build ${{ env.PATH_PROJECT }} --configuration Release --version-suffix ${{ steps.versioning.outputs.version }}

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack ${{ env.PATH_PROJECT }} --configuration Release -o ${{ github.workspace }}/out

    - name: Deploy Nuget.org
      run: dotnet nuget push "${{ github.workspace }}/out/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.SOURCE_NUGET }} --skip-duplicate
   
    - name: Deploy Github Package      
      run: dotnet nuget push "${{ github.workspace }}/out/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.SOURCE_GITHUB }} --skip-duplicate

    - name: Create Release
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: ${{ steps.versioning.outputs.version }}
        automatic_release_tag: ${{ steps.versioning.outputs.version }}
        prerelease: true

#testetesteteste